version: "3.9"

services:
  postgres:
    image: postgres:15
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: ashkar
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: redis
    restart: always
    ports:
      - "6379:6379"

  auth-service:
    build: ./be-authservices
    container_name: be-authservices
    restart: always
    ports:
      - "4001:4001"
    depends_on:
      - postgres
      - redis
    environment:
      DATABASE_URL: postgresql://ashkar:admin@postgres:5432/auth_db
      REDIS_URL: redis://redis:6379
      NODE_ENV: development
      JWT_ACCESS_SECRET: access_secret_123
    command: sh -c "npx prisma db push && npm start"

  attendance-service:
    build: ./be-attendanceservices
    container_name: be-attendanceservices
    restart: always
    ports:
      - "3001:3001"
    depends_on:
      - postgres
      - redis
    environment:
      DATABASE_URL: postgresql://ashkar:admin@postgres:5432/attendance_db
      REDIS_URL: redis://redis:6379
      AUTH_SERVICE_URL: http://auth-service:4001
      NODE_ENV: development
      JWT_ACCESS_SECRET: access_secret_123
    command: sh -c "npx prisma migrate deploy && npm start"

volumes:
  postgres_data:
